export {
  ProtocolRegistry,
  ProtocolFamilyRegistry,
  ProtocolCodeSchema,
  ProtocolFamilyCodeSchema,
  ConfigDataSchema,
  ConfigProtocolOptionsSchema,
  Amneziawg3ProtocolProfileSchema,
  Amneziawg3BrowserFingerprintSchema,
  Amneziawg3IntensitySchema,
  Amneziawg3ObfuscationLevelOrder,
  Amneziawg3ObfuscationPresets,
  getAmneziawg3ObfuscationLevel,
  buildAmneziawg3ConfigName,
  type ProtocolCode,
  type ProtocolFamilyCode,
  type ConfigData,
  type ConfigClientIdentifier,
  type ConfigProtocolOptions,
  type ConfigProtocolFields,
  type Amneziawg3ObfuscationOptions,
  type Amneziawg3ProtocolProfile,
  type Amneziawg3BrowserFingerprint,
  type Amneziawg3Intensity,
  type Amneziawg3ObfuscationLevel,
  type Amneziawg3ConfigObfuscationLevel,
} from "@vancloak/infrastructure/shared"
