export {
  ProtocolRegistry,
  ProtocolFamilyRegistry,
  ProtocolCodeSchema,
  ProtocolFamilyCodeSchema,
  ConfigDataSchema,
  ConfigProtocolOptionsSchema,
  Amneziawg2ProtocolProfileSchema,
  Amneziawg2BrowserFingerprintSchema,
  Amneziawg2IntensitySchema,
  Amneziawg2ObfuscationLevelOrder,
  Amneziawg2ObfuscationPresets,
  getAmneziawg2ObfuscationLevel,
  buildAmneziawg2ConfigName,
  type ProtocolCode,
  type ProtocolFamilyCode,
  type ConfigData,
  type ConfigClientIdentifier,
  type ConfigProtocolOptions,
  type ConfigProtocolFields,
  type Amneziawg2ObfuscationOptions,
  type Amneziawg2ProtocolProfile,
  type Amneziawg2BrowserFingerprint,
  type Amneziawg2Intensity,
  type Amneziawg2ObfuscationLevel,
  type Amneziawg2ConfigObfuscationLevel,
} from "@vancloak/infrastructure/shared"
